

export const vinilosTexturados = [
  {
    id: 'texturado-carbono-3d',
    imagenVinilo: "/imagenes/carbono.jpg",
    imagenVinilobig: "/imagenes/carbono.jpg",
    alt: "carbono3d",
    tipoVinilo: "Texturado",
    textura: "Simil Carbono 3D.",
    es_estampable: "No puede ser estampado.",
    caracteristica_color: "Colores inalterables.",
    adhesion: "Adhesion:Muy resistente.",
  },
  {
    id: 'texturado-madera-clara',
    imagenVinilo: "/imagenes/madera clara.jpg",
    imagenVinilobig: "/imagenes/madera clara.jpg",
    alt: "madera clara",
    tipoVinilo: "Texturado",
    textura: "Simil Madera Clara.",
    es_estampable: "No puede ser estampado.",
    caracteristica_color: "Colores inalterables.",
    adhesion: "Adhesion:Muy resistente.",
  },
  {
    id: 'texturado-madera-oscura',
    imagenVinilo: "/imagenes/madera oscura.jpg",
    imagenVinilobig: "/imagenes/madera oscura.jpg",
    alt: "Madera Oscura",
    tipoVinilo: "Texturado",
    textura: "Simil Madera Oscura.",
    es_estampable: "No puede ser estampado.",
    caracteristica_color: "Colores inalterables.",
    adhesion: "Adhesion:Muy resistente.",
  },
];

export const vinilosLisos = [
  {
    id: 'liso-blanco',
    imagenVinilo: "/imagenes/blanco.jpg",
    imagenVinilobig: "/imagenes/blanco.jpg",
    alt: "blanco",
    tipoVinilo: "Vinilo liso",
    textura: "Blanco con brillo y mate.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Colores con terminacion mate.",
    adhesion: "Adhesión firme, pero fácil de quitar. Ideal para quien le gusta cambiar la piel con frecuencia.",
  },
  {
    id: 'liso-negro-mate',
    imagenVinilo: "/imagenes/negro mate.jpg",
    imagenVinilobig: "/imagenes/negro mate.jpg",
    alt: "negro mate",
    tipoVinilo: "Vinilo liso.",
    textura: "Negro con brillo y mate.",
    es_estampable: "No puede ser estampado.",
    caracteristica_color: "Colores inalterables.",
    adhesion: "Adhesion:Muy resistente.",
  },
  {
    id: 'liso-fluo',
    imagenVinilo: "/imagenes/fluo.jpg",
    imagenVinilobig: "/imagenes/fluo.jpg",
    alt: "fluo",
    tipoVinilo: "Vinilo liso.",
    textura: "Fluo.",
    es_estampable: "Pueden ser estampados los colores claros.",
    caracteristica_color: "Colores inalterables y de gran contraste.",
    adhesion: "Adhesion:Muy resistente.",
  },
];

export const vinilosEspejados = [
  {
    id: 'espejado-liso',
    imagenVinilo: "/imagenes/espejado.jpg",
    imagenVinilobig: "/imagenes/espejado.jpg",
    alt: "espejado",
    tipoVinilo: "Vinilo espejado liso.",
    textura: "Espejado.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Colores con terminacion cromada y de gran contraste.",
    adhesion: "Adhesivo fuerte, un poco más rígido que los demás, muy durable.",
  },
  {
    id: 'espejado-cepillado',
    imagenVinilo: "/imagenes/cepillado.jpg",
    imagenVinilobig: "/imagenes/cepillado.jpg",
    alt: "cepillado",
    tipoVinilo: "Vinilo efecto cepillado",
    textura: "Espejado cepillado.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Colores con terminacion efecto cepillado y de gran contraste.",
    adhesion: "Adhesivo fuerte, un poco más rígido que los demás, muy durable.",
  },
  {
    id: 'espejado-estampado',
    imagenVinilo: "/imagenes/estampadoe.jpg",
    imagenVinilobig: "/imagenes/estampadoe.jpg",
    alt: "Estampado sobre espejado",
    tipoVinilo: "Vinilo espejado estampado.",
    textura: "100% personalizado.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Colores con terminacion cromada y de gran contraste.",
    adhesion: "Adhesivo fuerte, un poco más rígido que los demás, muy durable.",
  },
];

export const vinilosReflectivos = [
  {
    id: 'reflectivo-blanco',
    imagenVinilo: "/imagenes/reflectivo bl.jpg",
    imagenVinilobig: "/imagenes/reflectivo bl.jpg",
    alt: "Reflectivo blanco",
    tipoVinilo: "Vinilo Reflectivo blanco..",
    textura: "Blanco liso.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Terminacion reflectiva y de gran contraste.",
    adhesion: "Adhesivo fuerte, realmente queda como una piel, extra durable.",
  },
  {
    id: 'reflectivo-color',
    imagenVinilo: "/imagenes/reflectivo.jpg",
    imagenVinilobig: "/imagenes/reflectivo.jpg",
    alt: "Reflectivo color",
    tipoVinilo: "Vinilo Reflectivo en colores.",
    textura: "Reflectivo color.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Terminacion reflectiva y de gran contraste.",
    adhesion: "Adhesivo fuerte, realmente queda como una piel, extra durable.",
  },
  {
    id: 'reflectivo-estampado',
    imagenVinilo: "/imagenes/estampado reflec.jpg",
    imagenVinilobig: "/imagenes/estampado reflec.jpg",
    alt: "Estampado sobre reflectivo",
    tipoVinilo: "Vinilo Reflectivo estampado.",
    textura: "100% personalizado.",
    es_estampable: "Puede ser estampado.",
    caracteristica_color: "Colores firmes y fuertes con terminacion reflectiva y de gran contraste.",
    adhesion: "Adhesivo fuerte, realmente queda como una piel, extra durable.",
  },
];